"""Add assigned_employee_ids to projects

Revision ID: 99aa2daabb5c
Revises: bbb0fdaf6c34
Create Date: 2026-02-03 13:09:53.143354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99aa2daabb5c'
down_revision: Union[str, Sequence[str], None] = 'bbb0fdaf6c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_time_per_task', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('required_expertise', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('daily_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_duration_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allocated_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weekly_hours_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_tasks_allocated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productivity_override', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effective_week', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('allocations_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('allocations_pkey'))
    )
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leaves_pkey'))
    )
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    # ### end Alembic commands ###
