"""Add skills table

Revision ID: bbb0fdaf6c34
Revises: 
Create Date: 2026-02-03 12:15:44.569836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbb0fdaf6c34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('projects')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_productivity_logs_employee_id'), table_name='productivity_logs')
    op.drop_index(op.f('ix_productivity_logs_id'), table_name='productivity_logs')
    op.drop_index(op.f('ix_productivity_logs_project_id'), table_name='productivity_logs')
    op.drop_table('productivity_logs')
    op.drop_column('employees', 'skill_ratings')
    op.drop_column('employees', 'domain_experience')
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', sa.TEXT(), server_default=sa.text("'annotator'::text"), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('domain_experience', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('skill_ratings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('productivity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tasks_done', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours_worked', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('calculated_productivity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('productivity_logs_pkey'))
    )
    op.create_index(op.f('ix_productivity_logs_project_id'), 'productivity_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_productivity_logs_id'), 'productivity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_productivity_logs_employee_id'), 'productivity_logs', ['employee_id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leaves_pkey'))
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_time_per_task', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'medium'::text"), autoincrement=False, nullable=True),
    sa.Column('project_status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=True),
    sa.Column('required_expertise', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('daily_target', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('project_duration_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allocated_employees', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('sla_deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('weekly_target', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('required_weekly_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.CheckConstraint('allocated_employees >= 0', name='projects_allocated_employees_check'),
    sa.CheckConstraint('daily_target >= 0', name='projects_daily_target_check'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weekly_hours_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_tasks_allocated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productivity_override', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('effective_week', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('allocations_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('allocations_pkey'))
    )
    # ### end Alembic commands ###
